### ISSUE TITLE
Mock-up creation related to shared requirements

### ISSUE THREAD

**Issue by turanlioglu** [koglak/bounswe574-2022-gr2#12]
The mock-ups are a good way to describe the potential screens to encounter a project in real-life

**Comment by koglak** [comment]
https://www.figma.com/file/SmA7ZmwjzAK5P8znHRYYeZ/SWE-574?node-id=0%3A1

**Comment by koglak** [comment]
Mockup Screen page at Wiki of repo has been created: [Mockup Screens](https://github.com/koglak/bounswe574-2022-gr2/wiki/MockUp-Screens)

**Comment by koglak** [comment]
Event Page mock up screen is ready at Figma and shared on wiki page!

**Comment by turanlioglu** [comment]
Mock up for case-studies has been created via Figma, and added to the Wiki page.

**Comment by musentur** [comment]
MockUp Screen for Home Page has been added.

**Comment by bharaddur** [comment]
Mock up for Quiz screen has been added.

**Comment by koglak** [comment]
Closed.
