### ISSUE TITLE
Diagrams will be created/updated according to the mock-ups and requirements

### ISSUE THREAD

**Issue by turanlioglu** [koglak/bounswe574-2022-gr2#13]
Each group member will create diagrams according to their shared requirements

**Comment by koglak** [comment]
Event page use-cases are added to: [Diagrams](https://github.com/koglak/bounswe574-2022-gr2/wiki/Diagrams)

**Comment by turanlioglu** [comment]
Case Study Page 
Use-case diagram is added under: [Diagrams](https://github.com/koglak/bounswe574-2022-gr2/wiki/Diagrams)

**Comment by turanlioglu** [comment]
Case Study Page 
Sequence diagrams are added under: [Diagrams](https://github.com/koglak/bounswe574-2022-gr2/wiki/Diagrams)
