### ISSUE TITLE
User Scenario Creation

### ISSUE THREAD

**Issue by koglak** [koglak/bounswe574-2022-gr2#21]
Create user scenario for below pages:

- [x] Quiz Page / Mert Can Geyik
- [x] Case Study Page / Erdem Turanlıoğlu
- [x] Event Page / Kardelen Oğlakcıoğlu
- [ ] Profile Page / Ömer Bahar
- [x] Main Page / Mert Murat Şentürk

**Comment by koglak** [comment]
Wikipage has been created: [User Scenario](https://github.com/koglak/bounswe574-2022-gr2/wiki/User-Scenario)

**Comment by koglak** [comment]
Event page user scenario has been written.

**Comment by turanlioglu** [comment]
Case study user scenario has been created, and added to the Wiki page.

**Comment by bharaddur** [comment]
Quiz page user scenario has been created and added to the wiki

**Comment by musentur** [comment]
Main Page scenario has been created and added to the wiki
