### ISSUE TITLE
Web Annotation

### ISSUE THREAD

**Issue by koglak** [koglak/bounswe574-2022-gr2#26]
-Learn specification
-Apply to website

**Comment by turanlioglu** [comment]
[Documentation](https://docs.djangoproject.com/en/4.1/topics/db/aggregation/)

Sometimes you will need to retrieve values that are derived by summarizing or aggregating a collection of objects. This topic guide describes the ways that aggregate values can be generated and returned using Django queries.

[Tutorial](https://www.youtube.com/watch?v=KbwmdKl-QbI)
[Example](https://www.egehangundogdu.com/django-aggregate-annotate/)

**Comment by bharaddur** [comment]
Done

**Comment by bharaddur** [comment]
#47   reference given to the pull request
